# Generated by Django 4.1.1 on 2022-10-20 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_alter_comment_author'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-time_in'], 'verbose_name': 'Статья', 'verbose_name_plural': 'Статьи'},
        ),
    ]
